### ISSUE TITLE
Missing fig folder

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon_app_paper#1]
@goldingn looks like you have forgotten to commit the figs folder.... or maybe this was on purpose?

**Comment by timcdlucas** [comment]
It gets built when you compile so might be deliberate.

**Comment by AugustT** [comment]
But it means that the md file does not display correctly on GitHub

**Comment by goldingn** [comment]
Yup, as Tim says I was trying to avoid commuting the PDF, as version controlling binaries generally leads to big and sluggish repos and I wasn't planning on editing directly in GitHub.

Feel free to commit the image and/or change the compilation procedure though!

**Comment by AugustT** [comment]
Okay this makes sense
