### ISSUE TITLE
Add Greg's references

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon_app_paper#18]
@GregMci - thanks for your intro edits!

We're using [pandoc citeproc](http://pandoc.org/demo/example19/Extension-citations.html) for rendering citations. This just needs an `@` followed by the [tag corresponding to an entry in the `.bib` bibtex file](https://github.com/zoonproject/zoon_app_paper/blob/master/zoon_app.bib#L16) 

Like this:
`@McInerny2003` ->  McInerny _et al._ (2003)
`[@McInerny2003]` ->  (McInerny _et al._ 2003)

The entries in the .bib file are bibtex entries. I output mine [automatically from Mendeley](https://blog.mendeley.com/2011/10/25/howto-use-mendeley-to-create-citations-using-latex-and-bibtex/) and copy them into that folder. You can do something similar with [Endnote](http://www.rhizobia.co.nz/latex/convert) etc. too.

I'll probably have a bash at finding these references myself, but if you could **share a bibtex file for your citations** (even if it's your whole library), that would save me a lot of time!

**Comment by GregMci** [comment]
Will do... have to find a day for ZOON stuff this week
