### ISSUE TITLE
gh-publish

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon_app_paper#33]
https://github.com/ewanmellor/gh-publisher

Travis -> published pdf on github pages. Might be useful.

**Comment by goldingn** [comment]
This looks like a very similar approach to the automated pkgdown script running on the main zoon repo. That was such a hassle I don't have the stamina for it, but feel free to have a go if you want!

**Comment by goldingn** [comment]
(closing this now to be tidy, but please reopen if you want to try it out)

**Comment by timcdlucas** [comment]
No problem. Possibly too late in the day for it to be that useful now.
