### ISSUE TITLE
Fix Unix/OSX stuff

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon_app_paper#5]
So I have updated the ms to .rmd. This means the compile.sh will no longer work and that the tex_template folder should no longer be needed. Atleast this is my windows-Rstudio view on things. I will let @goldingn and @timcdlucas fix the mess I have made!

**Comment by goldingn** [comment]
Cool!

I'm not too familiar with Rmd. Presumably there's an R command (as well as the RStudio GUI approach) for building a doc? If so, you could make compile.sh into compile.R and change the readme execution code to:

 Rscript compile.R

template.tex isn't required in the bash version either, but I think it's prettier than the default :)
Surely knitr or whatever can pass a template to pandoc?

**Comment by timcdlucas** [comment]
The command is just `knitr::knit`.

From the command line it's `Rscript -e "library(knitr); knit('myfile.Rmd')"`

So could leave `compile.sh` as a shell file if preferred.

**Comment by goldingn** [comment]
But that won't run at the windows prompt (without cygwin or something) or in an R session.

BTW it's even shorter as:

"knitr::knit('myfile.Rmd')"

:)

**Comment by goldingn** [comment]
closed in that PR
