### ISSUE TITLE
Breeding bird lat lon

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon_app_paper#7]
I've been looking at the breeding bird data. 
I'm completely stuck trying to get their "Lat" and "Lon" values to correspond to actual latitude and longitude. 
Dunno if anyone happens to know more about how they dealt with this data in the first place?

Currently the lat  values range from about -1.5 to 1.5 and the lon values between -1.2 and 1.2 or so. 

The grids are apparently 25km squares.

**Comment by goldingn** [comment]
Heya, not sure which data you mean - in it's raw form in the BBS FTP site? Or the Carolina Wren stuff in `maxlike`?

**Comment by timcdlucas** [comment]
The carolina wren stuff in maxlike.

But I think in the end it doesn't matter if we're going to use that data only. 
It's internally consistent, I just couldn't get it to match bioclim rasters for example.

**Comment by goldingn** [comment]
These data are now in the temporary workflow in the ms
